version: "3.9"


volumes: 
  green_taxi_10_2016_postgres:

services:
  pgdatabase:
    container_name: postgres_container
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=green_taxi
    volumes:
      - "green_taxi_10_2016_postgres:/var/lib/postgresql/data:rw"  
      - "./m2_queries:/var/lib/:rw"
    ports:
      - "5432:5432"
    restart: on-failure

  preprocessing_ingestion:
    container_name: preprocessing_ingestion_container
    build: .
    image: preprocessing_ingestion:1.0
    volumes:
      - $(pwd)/data:/app/data
      - $(pwd)/src:/app/src

    depends_on:
      - pgdatabase
    restart: on-failure

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - pgdatabase
      - ingest_database
    ports:
      - "80:80"
    restart: on-failure


