
services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=green_taxi_etl
    volumes:
      - "green_taxi_10_2016_postgres:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"    
    networks:
      - airflow
volumes:
  green_taxi_10_2016_postgres:
networks:
  airflow:
    external:
      name: airflow_milestone4_default
